import Link from "next/link";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { ContextRail } from "@/components/ContextRail";
import { ErrorState } from "@/components/ErrorState";
import { StatusChip } from "@/components/StatusChip";
import { getInvestigation } from "@/lib/api/endpoints";
import { llmIdentity, railContext } from "@/lib/investigation";
import { STATE_COPY } from "@/lib/copy/states";

/**
 * Investigation layout — owns the persistent context rail (UX.md §4).
 *
 * This layout does not remount as the engineer moves between trace, signals,
 * anomaly, evaluation, evidence, hypotheses, report and provenance, so the rail
 * and the investigation-level banners genuinely persist across route changes and
 * are unaffected by any panel-level failure (UX.md §31).
 *
 * The record is fetched once here and again in each page; both calls hit Next's
 * fetch cache (`revalidateSeconds` on `getInvestigation`), so the ~217 KB body is
 * transferred once per revalidation window (design.md §11.3).
 */

const TABS: readonly { href: string; label: string }[] = [
  { href: "", label: "Workspace" },
  { href: "/trace", label: "Pipeline Trace" },
  { href: "/signals", label: "Signal Analysis" },
  { href: "/anomaly", label: "M7 Anomaly" },
  { href: "/evaluation", label: "M8 Evaluation" },
  { href: "/evidence", label: "Evidence" },
  { href: "/hypotheses", label: "Hypotheses" },
  { href: "/report", label: "Report" },
  { href: "/provenance", label: "Provenance" },
];

export default async function InvestigationLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ investigationId: string }>;
}) {
  const { investigationId } = await params;
  const result = await getInvestigation(investigationId);

  if (result.kind === "not-found") notFound();

  if (result.kind !== "ok") {
    return (
      <div className="p-[var(--ss-space-4)]">
        <ErrorState result={result} />
      </div>
    );
  }

  const record = result.data;
  const llm = llmIdentity(record);
  const hasErrors = Object.keys(record.errors).length > 0;

  return (
    <div className="flex min-h-full flex-col lg:h-full lg:flex-row lg:overflow-hidden">
      <ContextRail context={railContext(record)} />

      <div className="flex min-w-0 flex-1 flex-col lg:overflow-y-auto">
        {/* Investigation-level banners. These persist across every sub-route. */}
        <div className="flex flex-col gap-[var(--ss-space-2)] px-[var(--ss-space-4)] pt-[var(--ss-space-4)] lg:px-[var(--ss-space-6)]">
          {llm.mode === "MOCKED_INFERENCE" && (
            <Banner
              tone="attention"
              title={STATE_COPY.MOCKED_INFERENCE.title}
              body={STATE_COPY.MOCKED_INFERENCE.body}
            />
          )}
          {llm.mode === "LLM_PROVIDER_ERROR" && (
            <Banner
              tone="reject"
              title="LLM PROVIDER ERROR"
              body="A real inference request was attempted and the provider rejected or failed it. This is not a mocked run and not an unconfigured environment. The deterministic and evidence stages remain inspectable."
              detail={llm.error ?? undefined}
            />
          )}
          {llm.mode === "REAL_INFERENCE" && (
            <Banner
              tone="pass"
              title="REAL INFERENCE"
              body={`Candidate mechanisms in this investigation were generated by ${llm.provider ?? "the configured provider"} / ${llm.model ?? "unknown model"}.`}
            />
          )}
          {record.status === "PARTIAL" && (
            <Banner
              tone="attention"
              title={STATE_COPY.PARTIAL.title}
              body={STATE_COPY.PARTIAL.body}
              detail={
                hasErrors
                  ? `failed stages: ${Object.keys(record.errors).join(", ")}`
                  : undefined
              }
            />
          )}
          {record.errors["hypothesis_validation"] !== undefined && (
            <Banner
              tone="reject"
              title="HYPOTHESIS VALIDATION REJECTED"
              body="The retry budget was exhausted and the graph proceeded to the report agent anyway. This report exists despite a failed gate."
            />
          )}
          {record.errors["report_validation"] !== undefined && (
            <Banner
              tone="reject"
              title="REPORT VALIDATION REJECTED"
              body="The report was accepted as output with recorded validation issues."
            />
          )}
        </div>

        {/* Sub-navigation. */}
        <nav
          className="flex flex-wrap items-center gap-[var(--ss-space-1)] border-b border-[var(--ss-border-subtle)] px-[var(--ss-space-4)] py-[var(--ss-space-3)] lg:px-[var(--ss-space-6)]"
          aria-label="Investigation"
        >
          {TABS.map((tab) => (
            <Link
              key={tab.label}
              href={`/investigations/${investigationId}${tab.href}`}
              className="ss-field-label border border-[var(--ss-border-subtle)] px-[var(--ss-space-2)] py-[var(--ss-space-1)] text-[var(--ss-text-secondary)] hover:border-[var(--ss-accent)] hover:text-[var(--ss-text-primary)]"
              style={{ borderRadius: "var(--ss-radius-sm)" }}
            >
              {tab.label}
            </Link>
          ))}
          <span className="ml-auto flex items-center gap-[var(--ss-space-2)]">
            <Link
              href={`/modules/${encodeURIComponent(record.module_id)}`}
              className="ss-field-label border border-[var(--ss-border-strong)] px-[var(--ss-space-2)] py-[var(--ss-space-1)] text-[var(--ss-text-secondary)] hover:border-[var(--ss-accent)] hover:text-[var(--ss-text-primary)]"
              style={{ borderRadius: "var(--ss-radius-sm)" }}
            >
              Module context
            </Link>
            <StatusChip status={record.status} />
          </span>
        </nav>

        <div className="flex flex-col gap-[var(--ss-space-4)] p-[var(--ss-space-4)] lg:p-[var(--ss-space-6)]">
          {children}
        </div>
      </div>
    </div>
  );
}

function Banner({
  tone,
  title,
  body,
  detail,
}: {
  tone: "attention" | "reject" | "pass";
  title: string;
  body: string;
  detail?: string;
}) {
  const color =
    tone === "reject"
      ? "var(--ss-state-reject)"
      : tone === "pass"
        ? "var(--ss-state-pass)"
        : "var(--ss-state-attention-strong)";
  return (
    <div
      className={`flex flex-col gap-[var(--ss-space-1)] border p-[var(--ss-space-3)] ${
        tone === "attention" ? "ss-hatch" : ""
      }`}
      style={{
        borderColor: color,
        borderStyle: tone === "attention" ? "dashed" : "solid",
        borderRadius: "var(--ss-radius-sm)",
      }}
      role={tone === "reject" ? "alert" : undefined}
    >
      <span className="ss-field-label" style={{ color }}>
        {title}
      </span>
      <p className="text-[var(--ss-text-secondary)]" style={{ maxWidth: "var(--ss-measure-prose)" }}>
        {body}
      </p>
      {detail && <span className="ss-mono text-[var(--ss-text-muted)]">{detail}</span>}
    </div>
  );
}
