/**
 * The epistemic registers — frontend/UX.md §22, §44.4; design.md §12.4.
 *
 * This is the core scientific-design rule of the product: the same visual
 * treatment must never be used for a measured signal and an LLM hypothesis.
 *
 * Register differentiation is PRIMARILY STRUCTURAL — rule, surface elevation,
 * quotation, label. LLM REASONING is the single exception that carries a hue,
 * because UX.md §35 Rule 5 requires the generative boundary to be unmissable.
 */

export const REGISTERS = [
  "DATA",
  "CALCULATION",
  "RETRIEVED_EVIDENCE",
  "LLM_REASONING",
  "VALIDATION",
  "GROUND_TRUTH",
  "HUMAN_DECISION",
] as const;

export type Register = (typeof REGISTERS)[number];

export interface RegisterDefinition {
  /** Text shown by RegisterBadge. Never omitted — colour is never sufficient. */
  readonly label: string;
  /** Container classes. Tokens only; no literal colours (UX.md §44.10). */
  readonly surface: string;
  /** Value text colour. */
  readonly valueClass: string;
  /** Badge classes. */
  readonly badge: string;
  /** One-line explanation of what this register means, for tooltips/legends. */
  readonly meaning: string;
}

export const REGISTER_DEFINITIONS: Record<Register, RegisterDefinition> = {
  DATA: {
    label: "DATA",
    surface: "bg-[var(--ss-reg-data-surface)] border border-[var(--ss-border-subtle)]",
    valueClass: "text-[var(--ss-text-primary)]",
    badge: "text-[var(--ss-text-label)] border-[var(--ss-border-strong)]",
    meaning: "Measured or recorded value from the M6/M7 artifacts.",
  },
  CALCULATION: {
    label: "CALCULATED",
    surface:
      "bg-[var(--ss-reg-calc-surface)] border border-[var(--ss-border-subtle)] border-l-2 border-l-[var(--ss-reg-calc-rule)]",
    valueClass: "text-[var(--ss-text-primary)]",
    badge: "text-[var(--ss-text-label)] border-[var(--ss-reg-calc-rule)]",
    meaning: "Output of a fixed deterministic engineering tool, or an M8 metric.",
  },
  RETRIEVED_EVIDENCE: {
    label: "RETRIEVED EVIDENCE",
    surface:
      "bg-[var(--ss-reg-evidence-surface)] border border-[var(--ss-border-subtle)] border-l-2 border-l-[var(--ss-reg-evidence-rule)]",
    valueClass: "text-[var(--ss-text-secondary)]",
    badge: "text-[var(--ss-text-label)] border-[var(--ss-reg-evidence-rule)]",
    meaning: "Passage retrieved from a verified knowledge-base document.",
  },
  LLM_REASONING: {
    label: "LLM",
    surface:
      "bg-[var(--ss-reg-llm-surface)] border border-[var(--ss-reg-llm-border)]",
    valueClass: "text-[var(--ss-text-primary)]",
    badge: "text-[var(--ss-reg-llm-accent)] border-[var(--ss-reg-llm-border)]",
    meaning: "Generated by a language model. Requires engineering confirmation.",
  },
  VALIDATION: {
    label: "VALIDATION",
    surface:
      "bg-[var(--ss-reg-validation-surface)] border border-[var(--ss-border-subtle)]",
    valueClass: "text-[var(--ss-text-primary)]",
    badge: "text-[var(--ss-text-label)] border-[var(--ss-border-strong)]",
    meaning: "Outcome of an automated validation gate.",
  },
  GROUND_TRUTH: {
    label: "SYNTHETIC — EVALUATION ONLY",
    surface:
      "ss-hatch bg-[var(--ss-bg-surface)] border border-[var(--ss-reg-groundtruth-border)]",
    valueClass: "text-[var(--ss-text-secondary)]",
    badge: "text-[var(--ss-text-label)] border-[var(--ss-reg-groundtruth-border)]",
    meaning:
      "Injected synthetic ground truth. Never used for training and never a SmartESS output.",
  },
  HUMAN_DECISION: {
    label: "AWAITING ENGINEER REVIEW",
    surface:
      "bg-transparent border border-dashed border-[var(--ss-reg-human-border)]",
    valueClass: "text-[var(--ss-text-muted)]",
    badge: "text-[var(--ss-text-muted)] border-[var(--ss-reg-human-border)]",
    meaning:
      "Reserved for an engineer's decision. The backend stores no verdict (design.md §20.6).",
  },
};

export function registerDefinition(register: Register): RegisterDefinition {
  return REGISTER_DEFINITIONS[register];
}
